// src/app/pages/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthServiceService } from '../../services/auth-service.service';
import { Register } from '../../dto/register';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  errorMessage: string = '';
  successMessage: string = '';

  constructor(
    private authService: AuthServiceService,
    private router: Router,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.initForm();
  }

  initForm(): void {
    this.registerForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, Validators.pattern('^[0-9]{10}$')]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', [Validators.required]]
    }, {
      validators: this.passwordMatchValidator
    });
  }

  passwordMatchValidator(form: FormGroup) {
    const password = form.get('password')?.value;
    const confirmPassword = form.get('confirmPassword')?.value;
    
    if (password !== confirmPassword) {
      form.get('confirmPassword')?.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    return null;
  }

  get f() {
    return this.registerForm.controls;
  }

  onSubmit(): void {
    // Reset messages
    this.errorMessage = '';
    this.successMessage = '';

    if (this.registerForm.invalid) {
      return;
    }

    const registerData = new Register(
      this.registerForm.value.name,
      this.registerForm.value.email,
      this.registerForm.value.phone,
      this.registerForm.value.password
    );

    // Call register service
    this.authService.register(registerData).subscribe({
      next: (response) => {
        if (response.status === 'success') {
          this.successMessage = response.message;
          // Navigate to login page after 3 seconds
          setTimeout(() => {
            this.router.navigate(['/login']);
          }, 3000);
        } else {
          this.errorMessage = response.message;
        }
      },
      error: (error) => {
        this.errorMessage = error.error.message || 'Registration failed. Please try again.';
      }
    });
  }
}

<div class="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 relative overflow-hidden">
  <div class="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0zNiAzNGMwIDIuMjA5LTEuNzkxIDQtNCA0cy00LTEuNzkxLTQtNCAxLjc5MS00IDQtNCA0IDEuNzkxIDQgNHoiIGZpbGw9IiM2NjYiIGZpbGwtb3BhY2l0eT0iLjEiLz48L2c+PC9zdmc+')] opacity-20"></div>

  <div class="bg-white/90 backdrop-blur-sm p-8 rounded-2xl shadow-xl w-full max-w-md relative z-10">
    <h2 class="text-2xl font-bold mb-6 text-center text-gray-800">إنشاء حساب جديد</h2>
    
    @if(errorMessage){
      <div class="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg text-right">
        {{errorMessage == 'Invalid credentials' ? 'بيانات الاعتماد غير صالحة' : errorMessage}}
      </div>
    }

    @if(successMessage){
      <div class="mb-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded-lg text-right">
        {{successMessage == 'Registration successful!' ? 'تم التسجيل بنجاح!' : successMessage}}
      </div>
    }

    <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4" dir="rtl">
      <div>
        <label for="name" class="block text-sm font-medium text-gray-700 mb-1 text-right">الاسم الكامل</label>
        <input
          type="text"
          id="name"
          formControlName="name"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
          placeholder="أدخل اسمك الكامل"
          dir="rtl"
        />
        @if(f['name'].touched && f['name'].errors){
          <div class="text-red-500 text-sm mt-1 text-right">
            @if(f['name'].errors['required']){
              الاسم مطلوب
            }
            @if(f['name'].errors['minlength']){
              يجب أن يكون الاسم حرفين على الأقل
            }
          </div>
        }
      </div>

      <div>
        <label for="email" class="block text-sm font-medium text-gray-700 mb-1 text-right">البريد الإلكتروني</label>
        <input
          type="email"
          id="email"
          formControlName="email"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
          placeholder="أدخل بريدك الإلكتروني"
          dir="rtl"
        />
        @if(f['email'].touched && f['email'].errors){
          <div class="text-red-500 text-sm mt-1 text-right">
            @if(f['email'].errors['required']){
              البريد الإلكتروني مطلوب
            }
            @if(f['email'].errors['email']){
              الرجاء إدخال بريد إلكتروني صحيح
            }
          </div>
        }
      </div>

      <div>
        <label for="phone" class="block text-sm font-medium text-gray-700 mb-1 text-right">رقم الهاتف</label>
        <input
          type="tel"
          id="phone"
          formControlName="phone"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
          placeholder="أدخل رقم هاتفك"
          dir="rtl"
        />
        @if(f['phone'].touched && f['phone'].errors){
          <div class="text-red-500 text-sm mt-1 text-right">
            @if(f['phone'].errors['required']){
              رقم الهاتف مطلوب
            }
            @if(f['phone'].errors['pattern']){
              الرجاء إدخال رقم هاتف صحيح مكون من 10 أرقام
            }
          </div>
        }
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-gray-700 mb-1 text-right">كلمة المرور</label>
        <input
          type="password"
          id="password"
          formControlName="password"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
          placeholder="أدخل كلمة المرور"
          dir="rtl"
        />
        @if(f['password'].touched && f['password'].errors){
          <div class="text-red-500 text-sm mt-1 text-right">
            @if(f['password'].errors['required']){
              كلمة المرور مطلوبة
            }
            @if(f['password'].errors['minlength']){
              يجب أن تكون كلمة المرور 6 أحرف على الأقل
            }
          </div>
        }
      </div>

      <div>
        <label for="confirmPassword" class="block text-sm font-medium text-gray-700 mb-1 text-right">تأكيد كلمة المرور</label>
        <input
          type="password"
          id="confirmPassword"
          formControlName="confirmPassword"
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
          placeholder="تأكيد كلمة المرور"
          dir="rtl"
        />
        @if(f['confirmPassword'].touched && f['confirmPassword'].errors){
          <div class="text-red-500 text-sm mt-1 text-right">
            @if(f['confirmPassword'].errors['required']){
              تأكيد كلمة المرور مطلوب
            }
            @if(f['confirmPassword'].errors['passwordMismatch']){
              كلمات المرور غير متطابقة
            }
          </div>
        }
      </div>

      <button
        type="submit"
        [disabled]="registerForm.invalid"
        class="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition duration-200 disabled:bg-blue-300 disabled:cursor-not-allowed"
      >
        إنشاء حساب
      </button>
    </form>

    <div class="mt-6 text-center text-sm text-gray-500">
      لديك حساب بالفعل؟ <a routerLink="/login" class="text-blue-600 hover:underline cursor-pointer">تسجيل الدخول</a>
    </div>
  </div>
</div>

// app/register/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { authService } from '@/lib/auth-service'

export default function Register() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: ''
  })
  const [errors, setErrors] = useState({
    name: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: ''
  })
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')
  const router = useRouter()

  const validateForm = () => {
    const newErrors = {
      name: '',
      email: '',
      phone: '',
      password: '',
      confirmPassword: ''
    }
    let isValid = true

    if (!formData.name) {
      newErrors.name = 'الاسم مطلوب'
      isValid = false
    } else if (formData.name.length < 2) {
      newErrors.name = 'يجب أن يكون الاسم حرفين على الأقل'
      isValid = false
    }

    if (!formData.email) {
      newErrors.email = 'البريد الإلكتروني مطلوب'
      isValid = false
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'الرجاء إدخال بريد إلكتروني صحيح'
      isValid = false
    }

    if (!formData.phone) {
      newErrors.phone = 'رقم الهاتف مطلوب'
      isValid = false
    } else if (!/^[0-9]{10}$/.test(formData.phone)) {
      newErrors.phone = 'الرجاء إدخال رقم هاتف صحيح مكون من 10 أرقام'
      isValid = false
    }

    if (!formData.password) {
      newErrors.password = 'كلمة المرور مطلوبة'
      isValid = false
    } else if (formData.password.length < 6) {
      newErrors.password = 'يجب أن تكون كلمة المرور 6 أحرف على الأقل'
      isValid = false
    }

    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'تأكيد كلمة المرور مطلوب'
      isValid = false
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'كلمات المرور غير متطابقة'
      isValid = false
    }

    setErrors(newErrors)
    return isValid
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setErrorMessage('')
    setSuccessMessage('')

    if (!validateForm()) {
      return
    }

    try {
      const response = await authService.register({
        name: formData.name,
        email: formData.email,
        phone: formData.phone,
        password: formData.password
      })

      if (response.status === 'success') {
        setSuccessMessage(response.message)
        setTimeout(() => {
          router.push('/login')
        }, 3000)
      } else {
        setErrorMessage(response.message)
      }
    } catch (error: any) {
      setErrorMessage(error.message || 'Registration failed. Please try again.')
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
    // Clear error when user starts typing
    if (errors[name as keyof typeof errors]) {
      setErrors(prev => ({ ...prev, [name]: '' }))
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100 relative overflow-hidden">
      <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0zNiAzNGMwIDIuMjA5LTEuNzkxIDQtNCA0cy00LTEuNzkxLTQtNCAxLjc5MS00IDQtNCA0IDEuNzkxIDQgNHoiIGZpbGw9IiM2NjYiIGZpbGwtb3BhY2l0eT0iLjEiLz48L2c+PC9zdmc+')] opacity-20"></div>

      <div className="bg-white/90 backdrop-blur-sm p-8 rounded-2xl shadow-xl w-full max-w-md relative z-10">
        <h2 className="text-2xl font-bold mb-6 text-center text-gray-800">إنشاء حساب جديد</h2>
        
        {errorMessage && (
          <div className="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded-lg text-right">
            {errorMessage === 'Invalid credentials' ? 'بيانات الاعتماد غير صالحة' : errorMessage}
          </div>
        )}

        {successMessage && (
          <div className="mb-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded-lg text-right">
            {successMessage === 'Registration successful!' ? 'تم التسجيل بنجاح!' : successMessage}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4" dir="rtl">
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1 text-right">الاسم الكامل</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
              placeholder="أدخل اسمك الكامل"
              dir="rtl"
            />
            {errors.name && (
              <div className="text-red-500 text-sm mt-1 text-right">
                {errors.name}
              </div>
            )}
          </div>

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1 text-right">البريد الإلكتروني</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
              placeholder="أدخل بريدك الإلكتروني"
              dir="rtl"
            />
            {errors.email && (
              <div className="text-red-500 text-sm mt-1 text-right">
                {errors.email}
              </div>
            )}
          </div>

          <div>
            <label htmlFor="phone" className="block text-sm font-medium text-gray-700 mb-1 text-right">رقم الهاتف</label>
            <input
              type="tel"
              id="phone"
              name="phone"
              value={formData.phone}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
              placeholder="أدخل رقم هاتفك"
              dir="rtl"
            />
            {errors.phone && (
              <div className="text-red-500 text-sm mt-1 text-right">
                {errors.phone}
              </div>
            )}
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1 text-right">كلمة المرور</label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
              placeholder="أدخل كلمة المرور"
              dir="rtl"
            />
            {errors.password && (
              <div className="text-red-500 text-sm mt-1 text-right">
                {errors.password}
              </div>
            )}
          </div>

          <div>
            <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700 mb-1 text-right">تأكيد كلمة المرور</label>
            <input
              type="password"
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-right"
              placeholder="تأكيد كلمة المرور"
              dir="rtl"
            />
            {errors.confirmPassword && (
              <div className="text-red-500 text-sm mt-1 text-right">
                {errors.confirmPassword}
              </div>
            )}
          </div>

          <button
            type="submit"
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition duration-200"
          >
            إنشاء حساب
          </button>
        </form>

        <div className="mt-6 text-center text-sm text-gray-500">
          لديك حساب بالفعل؟ <Link href="/login" className="text-blue-600 hover:underline cursor-pointer">تسجيل الدخول</Link>
        </div>
      </div>
    </div>
  )
}
