// src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { HeaderComponent } from '../header/header.component';
import { AuthServiceService } from '../../services/auth-service.service';
import { Router } from '@angular/router';
import { ApiResponse } from '../../services/auth-service.service';
import { response } from 'express';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})
export class DashboardComponent implements OnInit{

  ResponseMessage: any;
  documents: Document[] = [];

  constructor(private authService: AuthServiceService, private router: Router){}

  ngOnInit(): void {
    this.getUserInfo();
    this.getDocuments();
  }

  getUserInfo(): void{ 
    this.authService.getUserInfo().subscribe({
      next: (response: ApiResponse) => {
        this.ResponseMessage = response;
      },
      error: (error:any) => {
        this.router.navigate(['/login']);
      }
    });
  }

  getDocuments(): void{
    this.authService.getDocuments().subscribe({
      next: response => this.documents = response.data,
      error: error => console.log(error.message)
    })
  }

}

interface Document{
  documentId: string,
  documentName: string,
  documentCategory: string,
  documentImage: any
}
<app-header></app-header>
<div>
    <div>
        <h5 class="bg-green-300 text-green-600">{{ResponseMessage?.message}}</h5>
    </div>
    <span>{{ResponseMessage?.data?.name}}</span>
</div>
<div class="p-6 bg-gray-100 min-h-screen">
    <h2 class="text-3xl font-bold mb-6">Documents</h2>
  
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-6">
      @for (doc of documents; track doc.documentId) {
        <div class="bg-white rounded-2xl shadow-md p-6">
            <img [src]="'data:image/png;base64,'+doc.documentImage" class="w-full h-48 object-cover rounded mb-3"/>
            <h3 class="text-xl font-semibold text-gray-800 mb-2">{{ doc.documentName }}</h3>
            <p class="text-sm text-gray-500 mb-1"><strong>Category:</strong> {{ doc.documentCategory }}</p>
          </div>
      }  

    </div>
</div>

// app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Header from '@/components/Header'
import { authService } from '@/lib/auth-service'

interface Document {
  documentId: string
  documentName: string
  documentCategory: string
  documentImage: string
}

interface ApiResponse {
  status: string
  message: string
  data: any
}

export default function Dashboard() {
  const [responseMessage, setResponseMessage] = useState<ApiResponse | null>(null)
  const [documents, setDocuments] = useState<Document[]>([])
  const router = useRouter()

  useEffect(() => {
    getUserInfo()
    getDocuments()
  }, [])

  const getUserInfo = async () => {
    try {
      const response = await authService.getUserInfo()
      setResponseMessage(response)
    } catch (error) {
      router.push('/login')
    }
  }

  const getDocuments = async () => {
    try {
      const response = await authService.getDocuments()
      setDocuments(response.data)
    } catch (error: any) {
      console.log(error.message)
    }
  }

  return (
    <>
      <Header />
      <div>
        <div>
          <h5 className="bg-green-300 text-green-600">{responseMessage?.message}</h5>
        </div>
        <span>{responseMessage?.data?.name}</span>
      </div>
      <div className="p-6 bg-gray-100 min-h-screen">
        <h2 className="text-3xl font-bold mb-6">Documents</h2>
      
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-6">
          {documents.map((doc) => (
            <div key={doc.documentId} className="bg-white rounded-2xl shadow-md p-6">
              <img 
                src={`data:image/png;base64,${doc.documentImage}`} 
                className="w-full h-48 object-cover rounded mb-3"
                alt={doc.documentName}
              />
              <h3 className="text-xl font-semibold text-gray-800 mb-2">{doc.documentName}</h3>
              <p className="text-sm text-gray-500 mb-1"><strong>Category:</strong> {doc.documentCategory}</p>
            </div>
          ))}
        </div>
      </div>
    </>
  )
}
